# -*- coding: utf-8 -*-
"""Windrose.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpT9FSonJJzCC21z_nX8ecApeHLM9c4f
"""

# National Centers for Environmental Information - NOAA
# This script extracts wind speed and direction to generate windrose plots
# Inputs: 
#         station_name - location/name of weather station
#         date_range   - date range of available data
#         station_ID   - numeric ID of the weather station
#         start_year   - earliest year data is available for station
#         end_year     - most recent year of data available for station
#
#        input values can be searched and gathered at:
#        https://www.ncei.noaa.gov/access/search/data-search/global-hourly
#
# Output: 
#         Windrose Plot

!pip install windrose
import pandas as pd 
import numpy as np 
import matplotlib.cm as cm
from matplotlib import pyplot as plt
from windrose import WindroseAxes
from matplotlib import colors
from google.colab import drive
drive.mount('drive')
APIhandle = 'https://www.ncei.noaa.gov/data/global-hourly/access/'

# USER INPUT PANE
station_name = 'HILO INTERNATIONAL AIRPORT 87, HI US'
date_range = '2018-01-01 to 2021-12-31'
station_ID = 94752099999
start_year = 2018
end_year = 2021

# Function for sending/receiving/processing API request
def readAPI(URL):
  
    df = pd.read_csv(URL, parse_dates=["DATE"], low_memory=False)
    df.index = df.DATE
    df = df.resample("H").first()
    df = df[['WND']].copy()
    df['Date'] = df.index
    df[['WindDirStr','A','B','WindSpeedStr','D']] = df.WND.str.split(',', expand=True)
    df['WindDir'] = pd.to_numeric(df['WindDirStr'])
    df['WindSpeed'] = pd.to_numeric(df['WindSpeedStr'])/10
    df = df.drop(['A','B','D','WindSpeedStr','WindDirStr','WND'],axis=1)
    df.reindex(['Date','WindDir','WindSpeed'])
    df = df[df.WindSpeed < 999]
    df_still = df[df.WindSpeed == 0]
    df_windy = df[df.WindSpeed > 0]
    df_windy = df_windy[df_windy.WindDir < 999]

    return df_windy

# Function for plotting windrose
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
def pltWindrose(station_name, date_range, df_windy):

    ax = WindroseAxes.from_ax()
    ax.set_title('WIND-ROSE PLOT OF\n' + station_name + '\n' + date_range)
    hist = ax.bar(df_windy.WindDir, df_windy.WindSpeed, normed=True, opening=0.8, edgecolor='white', bins=[1, 2, 4, 6, 8], cmap=cm.rainbow)
    ax.legend(title='Wind Speed [mph]')
    ax.set_legend(loc='best')

# MAIN
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Initiate
URL = APIhandle + str(start_year) + '/' + str(station_ID) + '.csv'
df = readAPI(URL)

# Loop remaining years + append dataframe
for i in range(2,end_year-start_year+2):
    URL = APIhandle + str(start_year+i-1) + '/' + str(station_ID) + '.csv'
    try:
          df = df.append(readAPI(URL), ignore_index = True, low_memory=False)
    except:
        continue

# Save Data
df.to_csv('data.csv')
!cp data.csv "drive/My Drive/"
# Plot windrose
pltWindrose(station_name, date_range, df)
plt